# Generated by Django 2.2.13 on 2020-11-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0025_userstats'),
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tiphistory',
            unique_together={('type', 'user')},
        ),
    ]
