# Generated by Django 2.2.13 on 2020-11-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20201106_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiphistory',
            options={'verbose_name': 'tip history', 'verbose_name_plural': 'tip histories'},
        ),
    ]
