# Generated by Django 2.2.24 on 2021-10-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_calltoaction_ctahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiphistory',
            name='last_attempt',
            field=models.DateTimeField(null=True),
        ),
    ]
