# Generated by Django 3.2.16 on 2022-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tiphistory_last_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiptype',
            name='tour_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
