# Generated by Django 3.2.14 on 2022-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tiphistory_last_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiptype',
            name='kind',
            field=models.CharField(choices=[('TT', 'Tool Tip'), ('DG', 'Dialog')], default='DG', max_length=2),
        ),
    ]
