# Generated by Django 2.2.4 on 2019-08-23 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('eventlog', '0001_initial'), ('eventlog', '0002_event'), ('eventlog', '0003_auto_20190823_1411')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('startedAtTime', models.DateTimeField(default=datetime.datetime.now)),
                ('endedAtTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('eventTime', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('ANNOTATION_EVENT', 'AnnotationEvent'), ('ASSESSMENT_EVENT', 'AssessmentEvent'), ('ASSESSMENT_ITEM_EVENT', 'AssessmentItemEvent'), ('ASSIGNABLE_EVENT', 'AssignableEvent'), ('EVENT', 'Event'), ('FORUM_EVENT', 'ForumEvent'), ('MEDIA_EVENT', 'MediaEvent'), ('MESSAGE_EVENT', 'MessageEvent'), ('NAVIGATION_EVENT', 'NavigationEvent'), ('GRADE_EVENT', 'GradeEvent'), ('SESSION_EVENT', 'SessionEvent'), ('THREAD_EVENT', 'ThreadEvent'), ('TOOL_USE_EVENT', 'ToolUseEvent'), ('VIEW_EVENT', 'ViewEvent')], max_length=8)),
                ('action', models.CharField(choices=[('ABANDONED', 'Abandoned'), ('ACTIVATED', 'Activated'), ('ADDED', 'Added'), ('ATTACHED', 'Attached'), ('BOOKMARKED', 'Bookmarked'), ('CHANGED_RESOLUTION', 'ChangedResolution'), ('CHANGED_SIZE', 'ChangedSize'), ('CHANGED_SPEED', 'ChangedSpeed'), ('CHANGED_VOLUME', 'ChangedVolume'), ('CLASSIFIED', 'Classified'), ('CLOSED_POPOUT', 'ClosedPopout'), ('COMMENTED', 'Commented'), ('COMPLETED', 'Completed'), ('CREATED', 'Created'), ('DEACTIVATED', 'Deactivated'), ('DELETED', 'Deleted'), ('DESCRIBED', 'Described'), ('DISABLED_CLOSED_CAPTIONING', 'DisabledClosedCaptioning'), ('DISLIKED', 'Disliked'), ('EARNED', 'Earned'), ('ENABLED_CLOSED_CAPTIONING', 'EnabledClosedCaptioning'), ('ENDED', 'Ended'), ('ENTERED_FULLSCREEN', 'EnteredFullScreen'), ('EXITED_FULLSCREEN', 'ExitedFullScreen'), ('FORWARDED_TO', 'ForwardedTo'), ('GRADED', 'Graded'), ('HID', 'Hid'), ('HIGHLIGHTED', 'Highlighted'), ('IDENTIFIED', 'Identified'), ('JUMPED_TO', 'JumpedTo'), ('LIKED', 'Liked'), ('LINKED', 'Linked'), ('LOGGED_IN', 'LoggedIn'), ('LOGGED_OUT', 'LoggedOut'), ('MARKED_AS_READ', 'MarkedAsRead'), ('MARKED_AS_UNREAD', 'MarkedAsUnread'), ('MODIFIED', 'Modified'), ('MUTED', 'Muted'), ('NAVIGATED_TO', 'NavigatedTo'), ('OPENED_POPOUT', 'OpenedPopout'), ('PAUSED', 'Paused'), ('POSTED', 'Posted'), ('QUESTIONED', 'Questioned'), ('RANKED', 'Ranked'), ('RECOMMENDED', 'Recommended'), ('REMOVED', 'Removed'), ('REPLIED', 'Replied'), ('RESET', 'Reset'), ('RESTARTED', 'Restarted'), ('RESUMED', 'Resumed'), ('RETRIEVED', 'Retrieved'), ('REVIEWED', 'Reviewed'), ('REWOUND', 'Rewound'), ('SEARCHED', 'Searched'), ('SHARED', 'Shared'), ('SHOWED', 'Showed'), ('SKIPPED', 'Skipped'), ('STARTED', 'Started'), ('SUBMITTED', 'Submitted'), ('SUBSCRIBED', 'Subscribed'), ('TAGGED', 'Tagged'), ('TIMED_OUT', 'TimedOut'), ('UNMUTED', 'Unmuted'), ('UNSUBSCRIBED', 'Unsubscribed'), ('USED', 'Used'), ('VIEWED', 'Viewed')], max_length=32)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
