# Generated by Django 2.2.4 on 2019-08-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0004_auto_20190823_1737'),
        ('roster', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.ClusiveUser'),
        ),
    ]
