# Generated by Django 2.2.4 on 2019-08-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0005_auto_20190823_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.ClusiveUser'),
        ),
    ]
