# Generated by Django 2.2.4 on 2019-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0006_auto_20190823_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='userAgent',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
