# Generated by Django 2.2.4 on 2019-08-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0008_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='membership',
            field=models.CharField(choices=[('GU', 'Guest'), ('ST', 'Student'), ('PA', 'Parent'), ('TE', 'Teacher'), ('RE', 'Researcher'), ('AD', 'Admin')], default='GU', max_length=2),
        ),
    ]
