# Generated by Django 2.2.4 on 2019-10-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0010_auto_20190903_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='control',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='page',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
