# Generated by Django 2.2.13 on 2020-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('messagequeue', '0001_initial'), ('messagequeue', '0002_auto_20200727_1243'), ('messagequeue', '0003_delete_message')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
