# Generated by Django 2.2.13 on 2020-07-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PC', 'Preference Change')], max_length=10)),
                ('timestamp', models.DateField()),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
