# Generated by Django 2.2.4 on 2019-10-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0016_auto_20190823_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
                ('rating', models.SmallIntegerField(null=True)),
                ('cued_lookups', models.SmallIntegerField(default=0)),
                ('free_lookups', models.SmallIntegerField(default=0)),
                ('cued', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.ClusiveUser')),
            ],
        ),
    ]
