# Generated by Django 2.2.9 on 2020-01-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmodel',
            name='interest',
            field=models.SmallIntegerField(default=0),
        ),
    ]
