# Generated by Django 2.2.3 on 2019-07-26 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site_id', models.CharField(default=uuid.uuid4, max_length=32, unique=True)),
                ('location', models.TextField(max_length=500)),
                ('language_code', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=2)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.CharField(default=uuid.uuid4, max_length=32, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Site')),
            ],
        ),
    ]
