# Generated by Django 2.2.3 on 2019-07-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_period_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='periods',
            field=models.ManyToManyField(to='roster.Period'),
        ),
    ]
