# Generated by Django 2.2.3 on 2019-07-26 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_clusiveuser_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='class_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
