# Generated by Django 2.2.4 on 2019-08-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_auto_20190807_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='permission',
            field=models.CharField(choices=[('PE', 'Permissioned'), ('PD', 'Pending'), ('DC', 'Declined'), ('WD', 'Withdrew'), ('TA', 'Test Account')], default='TA', max_length=2),
        ),
    ]
