# Generated by Django 2.2.4 on 2019-11-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_auto_20190823_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='permission',
            field=models.CharField(choices=[('PE', 'Permissioned'), ('PD', 'Pending'), ('DC', 'Declined'), ('WD', 'Withdrew'), ('TA', 'Test Account'), ('GU', 'Guest Account')], default='TA', max_length=2),
        ),
    ]
