# Generated by Django 2.2.10 on 2020-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0018_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=32)),
                ('set_description', models.CharField(max_length=256)),
                ('prefs_json', models.TextField()),
            ],
        ),
    ]
