# Generated by Django 2.2.10 on 2020-06-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0019_preferenceset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferenceset',
            old_name='set_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='preferenceset',
            old_name='set_name',
            new_name='name',
        ),
    ]
