# Generated by Django 2.2.13 on 2020-07-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0020_auto_20200603_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='current_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.Period'),
        ),
        migrations.AddField(
            model_name='clusiveuser',
            name='library_view',
            field=models.CharField(default='period', max_length=10),
        ),
        migrations.AlterField(
            model_name='clusiveuser',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='periods', to='roster.Period'),
        ),
    ]
