# Generated by Django 2.2.13 on 2020-07-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0021_auto_20200716_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='current_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.Period'),
        ),
        migrations.AlterField(
            model_name='clusiveuser',
            name='library_view',
            field=models.CharField(choices=[('all', 'All content'), ('public', 'Public content'), ('mine', 'My content'), ('period', 'Period assignments')], default='period', max_length=10),
        ),
    ]
