# Generated by Django 2.2.13 on 2020-09-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0023_clusiveuser_library_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='library_style',
            field=models.CharField(choices=[('bricks', 'bricks'), ('grid', 'grid'), ('list', 'list')], default='bricks', max_length=10),
        ),
        migrations.AlterField(
            model_name='clusiveuser',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='users', to='roster.Period'),
        ),
    ]
