# Generated by Django 2.2.13 on 2020-11-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0025_userstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'user stats', 'verbose_name_plural': 'user stats'},
        ),
    ]
