# Generated by Django 2.2.13 on 2021-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0026_auto_20201109_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='anon_id',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Anonymous identifier'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Class name'),
        ),
    ]
