# Generated by Django 2.2.13 on 2021-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0028_clusiveuser_unconfirmed_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='active_duration',
            field=models.DurationField(null=True),
        ),
    ]
