# Generated by Django 2.2.13 on 2021-03-30 20:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0030_auto_20210330_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='education_levels',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LE', 'Lower Elementary'), ('UE', 'Upper Elementary'), ('MS', 'Middle School'), ('HS', 'High School')], default=[], max_length=11, verbose_name='Education levels'),
        ),
    ]
