# Generated by Django 2.2.20 on 2021-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0031_clusiveuser_education_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='role',
            field=models.CharField(choices=[('GU', 'Guest'), ('ST', 'Student'), ('PA', 'Parent'), ('TE', 'Teacher'), ('RE', 'Researcher'), ('AD', 'Admin'), ('UN', 'Unknown')], default='GU', max_length=2),
        ),
    ]
