# Generated by Django 2.2.20 on 2021-06-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0033_mailinglistmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistmember',
            name='sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
