# Generated by Django 2.2.24 on 2021-08-13 12:16

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0035_userstats_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='education_levels',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LE', 'Lower Elementary'), ('UE', 'Upper Elementary'), ('MS', 'Middle School'), ('HS', 'High School')], default=[], max_length=11, verbose_name='Education levels'),
        ),
    ]
