# Generated by Django 2.2.24 on 2021-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0036_auto_20210813_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='period',
            name='type',
            field=models.CharField(choices=[('C', 'Created in Clusive'), ('G', 'Google Classroom')], default='C', max_length=4),
        ),
    ]
