# Generated by Django 2.2.24 on 2021-08-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0037_auto_20210819_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='type',
            new_name='data_source',
        ),
    ]
