# Generated by Django 2.2.24 on 2021-09-09 14:10

from django.db import migrations, models

from roster.models import RosterDataSource


def set_data_source_values(apps, schema_editor):
    ClusiveUser = apps.get_model('roster', 'ClusiveUser')
    SocialAccount = apps.get_model('socialaccount', 'SocialAccount')
    for cu in ClusiveUser.objects.all():
        if SocialAccount.objects.filter(user=cu.user).exists():
            cu.data_source = RosterDataSource.GOOGLE
            cu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0038_auto_20210825_2231'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='data_source',
            field=models.CharField(choices=[('C', 'Created in Clusive'), ('G', 'Google Classroom')], default='C', max_length=4),
        ),
        migrations.RunPython(set_data_source_values, migrations.RunPython.noop),
    ]
