# Generated by Django 2.2.24 on 2021-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0039_clusiveuser_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='clusiveuser',
            name='library_view',
            field=models.CharField(choices=[('all', 'All readings'), ('public', 'Public readings'), ('mine', 'My readings'), ('period', 'Period assignments')], default='period', max_length=10),
        ),
    ]
