# Generated by Django 2.2.24 on 2021-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0040_auto_20210925_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External ID'),
        ),
    ]
