# Generated by Django 2.2.24 on 2021-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0042_auto_20211006_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='student_activity_days',
            field=models.SmallIntegerField(default=0),
        ),
    ]
