# Generated by Django 2.2.24 on 2022-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0044_clusiveuser_student_activity_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
