# Generated by Django 2.2.24 on 2022-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0045_auto_20220209_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='library_view',
            field=models.CharField(choices=[('all', 'All readings'), ('public', 'Public readings'), ('mine', 'My readings'), ('starred', 'Starred readings'), ('period', 'Period assignments')], default='period', max_length=10),
        ),
    ]
