# Generated by Django 2.2.24 on 2022-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0046_auto_20220318_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookshareOrgUserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_user_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Bookshare organization')),
                ('account_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Bookshare account Id')),
                ('clusive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.ClusiveUser')),
            ],
        ),
    ]
