# Generated by Django 2.2.24 on 2022-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0047_clusiveuser_simplification_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='simplification_tool',
            field=models.CharField(choices=[('simplify', 'simplify'), ('translate', 'translate')], default='translate', max_length=10),
        ),
    ]
