# Generated by Django 2.2.28 on 2022-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0049_auto_20220412_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='transform_tool',
            field=models.CharField(choices=[('simplify', 'simplify'), ('translate', 'translate'), ('pictures', 'pictures')], default='translate', max_length=10),
        ),
    ]
