# Generated by Django 2.2.28 on 2022-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0050_auto_20220507_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='library_view',
            field=models.CharField(choices=[('all', 'All readings'), ('public', 'Public readings'), ('mine', 'Uploaded readings'), ('starred', 'Starred readings'), ('period', 'Period assignments')], default='period', max_length=10),
        ),
    ]
