# Generated by Django 3.2.14 on 2022-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0051_auto_20220526_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='library_sort',
            field=models.CharField(choices=[('title', 'title'), ('author', 'author'), ('recent', 'recent')], default='title', max_length=10),
        ),
    ]
