# Generated by Django 3.2.15 on 2022-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0052_clusiveuser_library_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglistmember',
            name='failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
