# Generated by Django 3.2.14 on 2022-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0053_mailinglistmember_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='dashboard_popular_view',
            field=models.CharField(default='', max_length=10),
        ),
    ]
