# Generated by Django 3.2.14 on 2022-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0054_clusiveuser_dashboard_popular_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveuser',
            name='dashboard_popular_view',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
