# Generated by Django 3.2.16 on 2022-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0055_alter_clusiveuser_dashboard_popular_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='reading_details_sort',
            field=models.CharField(choices=[('title', 'title'), ('time', 'time'), ('lastview', 'lastview')], default='title', max_length=10),
        ),
    ]
