# Generated by Django 3.2.16 on 2025-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0056_clusiveuser_reading_details_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusiveuser',
            name='agree_to_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
