# Generated by Django 2.2.13 on 2021-03-24 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0029_userstats_active_duration'),
        ('library', '0029_paradata_total_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionCheckResponse',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('comprehension_scale_response', models.IntegerField(choices=[(0, 'Nothing'), (1, 'A little'), (2, 'A lot')], default=0)),
                ('comprehension_free_response', models.TextField(default='')),
                ('book_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.BookVersion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roster.ClusiveUser')),
            ],
        ),
    ]
