# Generated by Django 2.2.13 on 2021-03-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20210324_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensioncheckresponse',
            name='comprehension_free_response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comprehensioncheckresponse',
            name='comprehension_scale_response',
            field=models.IntegerField(choices=[(0, 'Nothing'), (1, 'A little'), (2, 'A lot')], null=True),
        ),
    ]
