# Generated by Django 2.2.13 on 2021-03-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0029_paradata_total_time'),
        ('assessment', '0004_auto_20210324_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprehensioncheckresponse',
            name='book_version',
        ),
        migrations.AddField(
            model_name='comprehensioncheckresponse',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='library.Book'),
            preserve_default=False,
        ),
    ]
