# Generated by Django 2.2.20 on 2021-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_affectivecheckresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='annoyed_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='bored_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='calm_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='confused_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='curious_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='disappointed_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='frustrated_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='happy_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='interested_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='okay_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='sad_option_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='surprised_option_response',
            field=models.BooleanField(default=False),
        ),
    ]
