# Generated by Django 2.2.20 on 2021-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_clusiveratingresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusiveratingresponse',
            name='star_rating',
            field=models.SmallIntegerField(choices=[(1, "Really don't like it"), (2, "Don't like it"), (3, 'Like it'), (4, 'Really like it')]),
        ),
    ]
