# Generated by Django 2.2.24 on 2021-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_affectivebooktotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectivecheckresponse',
            name='affect_free_response',
            field=models.TextField(null=True),
        ),
    ]
