# Generated by Django 2.2.24 on 2022-01-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_affectivecheckresponse_affect_free_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensioncheckresponse',
            name='custom_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprehensioncheckresponse',
            name='comprehension_free_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprehensioncheckresponse',
            name='comprehension_scale_response',
            field=models.IntegerField(blank=True, choices=[(0, 'Nothing'), (1, 'A little'), (2, 'A lot')], null=True),
        ),
    ]
