# Generated by Django 2.2.28 on 2022-06-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20220126_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectivecheckresponse',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book'),
        ),
        migrations.AlterField(
            model_name='comprehensioncheckresponse',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book'),
        ),
    ]
