# Generated by Django 2.2.3 on 2019-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_auto_20190726_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='country_code',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='site',
            name='language_code',
            field=models.CharField(default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='site',
            name='timezone',
            field=models.CharField(default='EST', max_length=30),
        ),
    ]
