# Generated by Django 2.2.3 on 2019-08-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_auto_20190730_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusiveuser',
            old_name='subject_id',
            new_name='anon_id',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='class_id',
            new_name='anon_id',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_id',
            new_name='anon_id',
        ),
    ]
