# Generated by Django 2.2.4 on 2019-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_auto_20190806_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='language_code',
        ),
        migrations.AlterField(
            model_name='site',
            name='timezone',
            field=models.CharField(choices=[('America/Adak', 'America/Adak'), ('America/Anchorage', 'America/Anchorage'), ('America/Atikokan', 'America/Atikokan'), ('America/Blanc-Sablon', 'America/Blanc-Sablon'), ('America/Boise', 'America/Boise'), ('America/Cambridge_Bay', 'America/Cambridge Bay'), ('America/Chicago', 'America/Chicago'), ('America/Creston', 'America/Creston'), ('America/Dawson', 'America/Dawson'), ('America/Dawson_Creek', 'America/Dawson Creek'), ('America/Denver', 'America/Denver'), ('America/Detroit', 'America/Detroit'), ('America/Edmonton', 'America/Edmonton'), ('America/Fort_Nelson', 'America/Fort Nelson'), ('America/Glace_Bay', 'America/Glace Bay'), ('America/Goose_Bay', 'America/Goose Bay'), ('America/Halifax', 'America/Halifax'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Indiana/Tell_City', 'America/Indiana/Tell City'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('America/Indiana/Winamac', 'America/Indiana/Winamac'), ('America/Inuvik', 'America/Inuvik'), ('America/Iqaluit', 'America/Iqaluit'), ('America/Juneau', 'America/Juneau'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('America/Los_Angeles', 'America/Los Angeles'), ('America/Menominee', 'America/Menominee'), ('America/Metlakatla', 'America/Metlakatla'), ('America/Moncton', 'America/Moncton'), ('America/New_York', 'America/New York'), ('America/Nipigon', 'America/Nipigon'), ('America/Nome', 'America/Nome'), ('America/North_Dakota/Beulah', 'America/North Dakota/Beulah'), ('America/North_Dakota/Center', 'America/North Dakota/Center'), ('America/North_Dakota/New_Salem', 'America/North Dakota/New Salem'), ('America/Pangnirtung', 'America/Pangnirtung'), ('America/Phoenix', 'America/Phoenix'), ('America/Rainy_River', 'America/Rainy River'), ('America/Rankin_Inlet', 'America/Rankin Inlet'), ('America/Regina', 'America/Regina'), ('America/Resolute', 'America/Resolute'), ('America/Sitka', 'America/Sitka'), ('America/St_Johns', 'America/St Johns'), ('America/Swift_Current', 'America/Swift Current'), ('America/Thunder_Bay', 'America/Thunder Bay'), ('America/Toronto', 'America/Toronto'), ('America/Vancouver', 'America/Vancouver'), ('America/Whitehorse', 'America/Whitehorse'), ('America/Winnipeg', 'America/Winnipeg'), ('America/Yakutat', 'America/Yakutat'), ('America/Yellowknife', 'America/Yellowknife'), ('Pacific/Honolulu', 'Pacific/Honolulu')], default='America/New_York', max_length=30),
        ),
    ]
