# Generated by Django 2.2.4 on 2019-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_auto_20190806_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='country_code',
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='state_or_province',
            field=models.CharField(default='', max_length=50),
        ),
    ]
