# Generated by Django 2.2.4 on 2019-08-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_auto_20190806_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='location',
        ),
    ]
