# Generated by Django 2.2.4 on 2019-08-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='endedAtTime',
            field=models.DateTimeField(null=True),
        ),
    ]
