# Generated by Django 2.2.4 on 2019-08-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_auto_20190823_2029'),
        ('eventlog', '0007_session_useragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.Period'),
        ),
    ]
