# Generated by Django 2.2.13 on 2020-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0011_auto_20191011_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activeDuration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='loadTime',
            field=models.DurationField(null=True),
        ),
    ]
