# Generated by Django 2.2.13 on 2020-10-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0012_auto_20201029_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document_version',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
