# Generated by Django 2.2.13 on 2020-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0015_event_document_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document_href',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
