# Generated by Django 2.2.13 on 2020-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0016_event_document_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='document_progression',
            field=models.FloatField(null=True),
        ),
    ]
