# Generated by Django 2.2.13 on 2020-11-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0018_event_book_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='document',
        ),
        migrations.RemoveField(
            model_name='event',
            name='document_version',
        ),
    ]
