# Generated by Django 2.2.13 on 2020-11-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0020_auto_20201116_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='document_href',
            new_name='resource_href',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='document_progression',
            new_name='resource_progression',
        ),
    ]
