# Generated by Django 2.2.13 on 2020-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0021_auto_20201120_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
