# Generated by Django 2.2.13 on 2021-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0022_event_parent_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='control',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
