# Generated by Django 2.2.13 on 2021-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0023_auto_20210128_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='book_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
