# Generated by Django 2.2.13 on 2021-03-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0025_auto_20210316_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='activeDuration',
            new_name='active_duration',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='loadTime',
            new_name='load_time',
        ),
    ]
