# Generated by Django 2.2.13 on 2021-03-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0026_auto_20210316_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginsession',
            old_name='endedAtTime',
            new_name='ended_at_time',
        ),
        migrations.RenameField(
            model_name='loginsession',
            old_name='startedAtTime',
            new_name='started_at_time',
        ),
        migrations.RenameField(
            model_name='loginsession',
            old_name='userAgent',
            new_name='user_agent',
        ),
        migrations.AddField(
            model_name='loginsession',
            name='active_duration',
            field=models.DurationField(null=True),
        ),
    ]
