# Generated by Django 2.2.20 on 2021-04-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0027_auto_20210320_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
