# Generated by Django 2.2.20 on 2021-04-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0028_event_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.ClusiveUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='membership',
            field=models.CharField(choices=[('GU', 'Guest'), ('ST', 'Student'), ('PA', 'Parent'), ('TE', 'Teacher'), ('RE', 'Researcher'), ('AD', 'Admin'), ('UN', 'Unknown')], default='GU', max_length=2),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.ClusiveUser'),
        ),
    ]
