# Generated by Django 2.2.28 on 2022-06-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(choices=[('NP', 'Noun Project'), ('FI', 'Flaticon')], max_length=4)),
                ('word', models.CharField(max_length=256)),
                ('icon_id', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
